/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			colors: {
				'primary': 'var(--md-sys-color-primary)',
				'surface-tint': 'var(--md-sys-color-surface-tint)',
				'on-primary': 'var(--md-sys-color-on-primary)',
				'primary-container': 'var(--md-sys-color-primary-container)',
				'on-primary-container': 'var(--md-sys-color-on-primary-container)',
				'secondary': 'var(--md-sys-color-secondary)',
				'on-secondary': 'var(--md-sys-color-on-secondary)',
				'secondary-container': 'var(--md-sys-color-secondary-container)',
				'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
				'tertiary': 'var(--md-sys-color-tertiary)',
				'on-tertiary': 'var(--md-sys-color-on-tertiary)',
				'tertiary-container': 'var(--md-sys-color-tertiary-container)',
				'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
				'error': 'var(--md-sys-color-error)',
				'on-error': 'var(--md-sys-color-on-error)',
				'error-container': 'var(--md-sys-color-error-container)',
				'on-error-container': 'var(--md-sys-color-on-error-container)',
				'background': 'var(--md-sys-color-background)',
				'on-background': 'var(--md-sys-color-on-background)',
				'surface': 'var(--md-sys-color-surface)',
				'on-surface': 'var(--md-sys-color-on-surface)',
				'surface-variant': 'var(--md-sys-color-surface-variant)',
				'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
				'outline': 'var(--md-sys-color-outline)',
				'outline-variant': 'var(--md-sys-color-outline-variant)',
				'shadow': 'var(--md-sys-color-shadow)',
				'scrim': 'var(--md-sys-color-scrim)',
				'inverse-surface': 'var(--md-sys-color-inverse-surface)',
				'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
				'inverse-primary': 'var(--md-sys-color-inverse-primary)',
				'primary-fixed': 'var(--md-sys-color-primary-fixed)',
				'on-primary-fixed': 'var(--md-sys-color-on-primary-fixed)',
				'primary-fixed-dim': 'var(--md-sys-color-primary-fixed-dim)',
				'on-primary-fixed-variant': 'var(--md-sys-color-on-primary-fixed-variant)',
				'secondary-fixed': 'var(--md-sys-color-secondary-fixed)',
				'on-secondary-fixed': 'var(--md-sys-color-on-secondary-fixed)',
				'secondary-fixed-dim': 'var(--md-sys-color-secondary-fixed-dim)',
				'on-secondary-fixed-variant': 'var(--md-sys-color-on-secondary-fixed-variant)',
				'tertiary-fixed': 'var(--md-sys-color-tertiary-fixed)',
				'on-tertiary-fixed': 'var(--md-sys-color-on-tertiary-fixed)',
				'tertiary-fixed-dim': 'var(--md-sys-color-tertiary-fixed-dim)',
				'on-tertiary-fixed-variant': 'var(--md-sys-color-on-tertiary-fixed-variant)',
				'surface-dim': 'var(--md-sys-color-surface-dim)',
				'surface-bright': 'var(--md-sys-color-surface-bright)',
				'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
				'surface-container-low': 'var(--md-sys-color-surface-container-low)',
				'surface-container': 'var(--md-sys-color-surface-container)',
				'surface-container-high': 'var(--md-sys-color-surface-container-high)',
				'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
				'carrera-Bioquímica': 'var(--carrera-Bioquímica)',
				'carrera-Ingeniería-en-Agrimensura': 'var(--carrera-Ingeniería-en-Agrimensura)',
				'carrera-Ingeniería-Eléctrica': 'var(--carrera-Ingeniería-Eléctrica)',
				'carrera-Ingeniería-en-Electrónica': 'var(--carrera-Ingeniería-en-Electrónica)',
				'carrera-Licenciatura-en-Ciencias-Biológicas': 'var(--carrera-Licenciatura-en-Ciencias-Biológicas)',
				'carrera-Licenciatura-en-Ciencias-Físicas': 'var(--carrera-Licenciatura-en-Ciencias-Físicas)',
				'carrera-Licenciatura-en-Ciencias-Químicas': 'var(--carrera-Licenciatura-en-Ciencias-Químicas)',
				'carrera-Licenciatura-en-Matemática': 'var(--carrera-Licenciatura-en-Matemática)',
				'carrera-Licenciatura-en-Sistemas-de-Información': 'var(--carrera-Licenciatura-en-Sistemas-de-Información)',
				'carrera-Licenciatura-en-Didáctica-de-la-Matemática': 'var(--carrera-Licenciatura-en-Didáctica-de-la-Matemática)',
				'carrera-Profesorado-en-Biología': 'var(--carrera-Profesorado-en-Biología)',
				'carrera-Profesorado-en-Ciencias-Químicas-y-del-Ambiente': 'var(--carrera-Profesorado-en-Ciencias-Químicas-y-del-Ambiente)',
				'carrera-Profesorado-en-Física': 'var(--carrera-Profesorado-en-Física)',
				'carrera-Profesorado-en-Matemática': 'var(--carrera-Profesorado-en-Matemática)',
				'carrera-Profesorado-Universitario-en-Informática': 'var(--carrera-Profesorado-Universitario-en-Informática)',
			},
			/* ---- Fuentes ---- */
			fontFamily: {
				"display-large-font-family": "Poppins, sans-serif",
				"display-medium-font-family": "Poppins, sans-serif",
				"display-small-font-family": "Poppins, sans-serif",

				"headline-large-font-family": "Poppins, sans-serif",
				"headline-medium-font-family": "Poppins, sans-serif",
				"headline-small-font-family": "Poppins, sans-serif",

				"title-large-font-family": "Poppins, sans-serif",
				"title-medium-font-family": "Poppins, sans-serif",
				"title-small-font-family": "Poppins, sans-serif",

				"label-large-font-family": "Poppins, sans-serif",
				"label-medium-font-family": "Poppins, sans-serif",
				"label-small-font-family": "Poppins, sans-serif",

				"body-large-font-family": "Poppins, sans-serif",
				"body-medium-font-family": "Poppins, sans-serif",
				"body-small-font-family": "Poppins, sans-serif",
			},
			fontSize: {
				"display-large-font-size": "72px",
				"display-medium-font-size": "45px",
				"display-small-font-size": "36px",
				"display-medium-size": "45px",
				"display-small-size": "36px",

				"headline-large-font-size": "32px",
				"headline-medium-font-size": "28px",
				"headline-small-font-size": "24px",
				"headline-large-size": "32px",
				"headline-medium-size": "28px",
				"headline-small-size": "24px",

				"title-large-font-size": "22px",
				"title-medium-font-size": "16px",
				"title-small-font-size": "14px",
				"title-large-size": "22px",
				"title-medium-size": "16px",
				"title-small-size": "14px",
				"label-large-size": "14px",
				"label-medium-size": "12px",
				"label-small-size": "11px",

				"label-large-font-size": "14px",
				"label-medium-font-size": "12px",
				"label-small-font-size": "11px",
				"label-large-size": "14px",
				"label-medium-size": "12px",
				"label-small-size": "11px",

				"body-large-font-size": "16px",
				"body-medium-font-size": "14px",
				"body-small-font-size": "12px",
				"body-large-size": "16px",
				"body-medium-size": "14px",
				"body-small-size": "12px",
			},
			fontWeight: {
				"display-large-font-weight": "700",
				"display-medium-font-weight": "700",
				"display-small-font-weight": "700",

				"headline-large-font-weight": "500",
				"headline-medium-font-weight": "500",
				"headline-small-font-weight": "500",

				"title-large-font-weight": "500",
				"title-medium-font-weight": "500",
				"title-small-font-weight": "500",

				"label-large-font-weight": "500",
				"label-medium-font-weight": "500",
				"label-small-font-weight": "500",

				"body-large-font-weight": "400",
				"body-medium-font-weight": "400",
				"body-small-font-weight": "400",
			},
			lineHeight: {
				"display-large-line-height": "64px",
				"display-medium-line-height": "52px",
				"display-small-line-height": "44px",
				"display-large-line-height": "64px",
				"display-medium-line-height": "52px",
				"display-small-line-height": "44px",

				"headline-large-line-height": "40px",
				"headline-medium-line-height": "36px",
				"headline-small-line-height": "32px",
				"headline-large-line-height": "40px",
				"headline-medium-line-height": "36px",
				"headline-small-line-height": "32px",

				"title-large-line-height": "28px",
				"title-medium-line-height": "24px",
				"title-small-line-height": "20px",
				"title-large-line-height": "28px",
				"title-medium-line-height": "24px",
				"title-small-line-height": "20px",

				"label-large-line-height": "20px",
				"label-medium-line-height": "16px",
				"label-small-line-height": "16px",
				"label-large-line-height": "20px",
				"label-medium-line-height": "16px",
				"label-small-line-height": "16px",

				"body-large-line-height": "24px",
				"body-medium-line-height": "20px",
				"body-small-line-height": "16px",
				"body-large-line-height": "24px",
				"body-medium-line-height": "20px",
				"body-small-line-height": "16px",
			},
			letterSpacing: {
				"display-medium-tracking": "",

				"headline-large-tracking": "",
				"headline-small-tracking": "",

				"title-large-tracking": "",
				"title-medium-tracking": "0.15px",
				"title-small-tracking": "0.1px",

				"label-large-tracking": "0.1px",
				"label-medium-tracking": "0.5px",
				"label-small-tracking": "0.5px",

				"body-large-tracking": "0.5px",
				"body-medium-tracking": "0.25px",
				"body-small-tracking": "0.4px",
			},
			boxShadow: {
				1: "var(--m3-elevation-1-box-shadow)",
				2: "var(--m3-elevation-2-box-shadow)",
				3: "var(--m3-elevation-3-box-shadow)",
				4: "var(--m3-elevation-4-box-shadow)",
				5: "var(--m3-elevation-5-box-shadow)",
			},
			darkMode: 'class',
		},
	},
	plugins: [],
	darkMode: 'selector',
}
